
project_id = "embuxlxugjkjgsusrmlx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"

[storage]
enabled = true

[edge-functions]
enabled = true

[functions.translate-card]
verify_jwt = false

[functions.search-with-gpt]
verify_jwt = false

[functions.send-review-notification]
verify_jwt = false

[functions.restaurants-search]
verify_jwt = false
