import { Helmet } from "react-helmet";
import { 
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger 
} from "@/components/ui/accordion";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

export default function FAQ() {
  const faqCategories = [
    {
      id: "general",
      label: "General Information",
      questions: [
        {
          question: "What is the Allergy-Friendly Hotel Finder?",
          answer: "Our platform helps travelers with food allergies find hotels that cater to their dietary needs. We provide recommendations, reviews, and essential information about hotels worldwide that offer allergy-friendly services."
        },
        {
          question: "How do you determine if a hotel is allergy-friendly?",
          answer: "We analyze hotel policies, guest reviews, and direct communication with hotel staff to assess their ability to accommodate guests with food allergies."
        },
        {
          question: "Is the website available in languages other than English?",
          answer: "Currently, our website is available in English. However, we are working on adding more language support in the future."
        },
        {
          question: "How is the information on your website sourced?",
          answer: "At this stage, all the information on our website is generated by AI based on publicly available data and analysis of hotel policies. While we strive for accuracy, we encourage travelers to verify details directly with the hotels before booking. In the future, we plan to incorporate user reviews and direct hotel contributions to enhance the reliability of our recommendations."
        }
      ]
    },
    {
      id: "booking",
      label: "Booking & Reservations",
      questions: [
        {
          question: "Can I book a hotel directly through your website?",
          answer: "Not yet. We provide recommendations and direct you to official hotel booking pages where you can make a reservation."
        },
        {
          question: "Do you offer special rates or discounts?",
          answer: "We are working on partnerships with hotels to offer exclusive deals. Stay tuned for updates!"
        },
        {
          question: "How can I make a special request for my food allergies when booking?",
          answer: "We recommend contacting the hotel directly after booking and mentioning your dietary restrictions to ensure they can accommodate your needs."
        }
      ]
    },
    {
      id: "services",
      label: "Allergy-Friendly Services",
      questions: [
        {
          question: "Do hotels on your platform offer allergen-free meals?",
          answer: "Some hotels provide dedicated allergy-friendly menus, while others may be able to accommodate specific dietary needs upon request. Each hotel listing includes details about their food allergy policies."
        },
        {
          question: "What types of allergies do you cover?",
          answer: "Our platform primarily focuses on common food allergies, such as dairy, eggs, wheat, peanuts, tree nuts, shellfish, soy, and fish. However, we also provide information about hotels accommodating other allergies, such as pet or dust allergies."
        },
        {
          question: "How can I be sure a hotel follows strict allergen safety protocols?",
          answer: "We recommend checking guest reviews, contacting the hotel before your stay, and confirming their food handling policies with the hotel staff."
        }
      ]
    },
    {
      id: "reviews",
      label: "User Reviews",
      questions: [
        {
          question: "Can I leave a review about my stay at an allergy-friendly hotel?",
          answer: "Absolutely! Your feedback helps others make informed decisions. You can submit reviews on each hotel's page."
        },
        {
          question: "How do you verify hotel reviews?",
          answer: "We encourage detailed, honest reviews from real travelers. Our team monitors reviews for accuracy and may reach out for verification if needed."
        }
      ]
    },
    {
      id: "technical",
      label: "Technical Support",
      questions: [
        {
          question: "Is the Allergy-Friendly Hotel Finder free to use?",
          answer: "Yes! Our platform is completely free for travelers looking for allergy-friendly accommodations."
        },
        {
          question: "How can I contact support for help?",
          answer: "You can reach out to us via our contact page or email us at support@allergytravel.com."
        },
        {
          question: "I found incorrect information on a hotel listing. How can I report it?",
          answer: "Please use the \"Report an Issue\" button on the hotel's page or email us with the details."
        }
      ]
    },
    {
      id: "future",
      label: "Future Updates",
      questions: [
        {
          question: "Are you planning to add more destinations?",
          answer: "Yes! We continuously expand our database to include more hotels in allergy-friendly destinations worldwide."
        },
        {
          question: "Will you add a feature for travelers to connect with each other?",
          answer: "We are exploring the possibility of a community forum where travelers can share experiences and tips."
        },
        {
          question: "Can I suggest a hotel to be featured on your platform?",
          answer: "Of course! If you know of an allergy-friendly hotel, please let us know through our \"Suggest a Hotel\" page."
        }
      ]
    }
  ];

  return (
    <div className="min-h-screen bg-white">
      <Helmet>
        <title>Frequently Asked Questions | Allergy Free Travel</title>
        <meta name="description" content="Find answers to common questions about allergy-friendly travel, hotel accommodations, and our platform." />
        <meta name="keywords" content="FAQ, allergy-friendly travel, food allergies, hotel accommodations, dietary restrictions, travel questions" />
      </Helmet>

      <main className="container mx-auto px-4 py-12 max-w-7xl">
        <div className="max-w-4xl mx-auto space-y-10">
          <section className="text-center space-y-4">
            <h1 className="text-3xl sm:text-4xl md:text-5xl font-display font-bold text-foreground">
              Frequently Asked Questions
            </h1>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Find answers to common questions about allergy-friendly travel, hotels, and our platform.
            </p>
          </section>

          <div className="bg-white rounded-lg border p-6 shadow-sm">
            <Tabs defaultValue="general" className="w-full">
              <div className="overflow-x-auto pb-4">
                <TabsList className="mb-6 h-auto flex flex-wrap sm:flex-nowrap gap-2 w-max min-w-full">
                  {faqCategories.map((category) => (
                    <TabsTrigger 
                      key={category.id} 
                      value={category.id} 
                      className="whitespace-nowrap px-4 py-2 flex-shrink-0"
                    >
                      {category.label}
                    </TabsTrigger>
                  ))}
                </TabsList>
              </div>
              
              {faqCategories.map((category) => (
                <TabsContent key={category.id} value={category.id} className="pt-4">
                  <h2 className="text-xl font-semibold mb-6">{category.label}</h2>
                  <Accordion type="single" collapsible className="w-full space-y-4">
                    {category.questions.map((item, index) => (
                      <AccordionItem key={index} value={`item-${index}`} className="border rounded-md px-4">
                        <AccordionTrigger className="text-left font-medium py-4">
                          {item.question}
                        </AccordionTrigger>
                        <AccordionContent className="text-muted-foreground pb-4">
                          {item.answer}
                        </AccordionContent>
                      </AccordionItem>
                    ))}
                  </Accordion>
                </TabsContent>
              ))}
            </Tabs>
          </div>
        </div>
      </main>
    </div>
  );
}
