// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-destinations.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
import { destinations } from "npm:@/data/destinations-list";
var list_destinations_default = defineTool({
  name: "list_destinations",
  title: "List destinations",
  description: "List all allergy-friendly travel destination guides on the site, with id, name, country, and a short description. Use the returned id with get_destination_guide.",
  inputSchema: {
    query: z.string().optional().describe("Optional case-insensitive filter matched against name, country, or description.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }) => {
    const q = query?.trim().toLowerCase();
    const items = destinations.filter(
      (d) => !q ? true : [d.name, d.country, d.description, d.subtitle].filter(Boolean).some((v) => String(v).toLowerCase().includes(q))
    ).map((d) => ({
      id: d.id,
      name: d.name,
      country: d.country,
      description: d.description
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { count: items.length, destinations: items }
    };
  }
});

// src/lib/mcp/tools/get-destination-guide.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { destinationData } from "npm:@/data/destination-data";
import { destinations as destinations2 } from "npm:@/data/destinations-list";
function toText(intro) {
  if (!intro) return "";
  if (typeof intro === "string") return intro;
  if (Array.isArray(intro)) return intro.join("\n\n");
  if (typeof intro === "object") {
    const o = intro;
    return [o.title, o.description, o.quickTip].filter(Boolean).join("\n\n");
  }
  return "";
}
var get_destination_guide_default = defineTool2({
  name: "get_destination_guide",
  title: "Get destination guide",
  description: "Get the full allergy-friendly guide for one destination by its id (from list_destinations): intro, hotels, restaurants, FAQs, and travel tips.",
  inputSchema: {
    id: z2.string().min(1).describe("Destination id, e.g. 'london', 'paris', 'tuscany'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const key = id.trim().toLowerCase();
    const content = destinationData[key];
    const meta = destinations2.find((d) => d.id === key);
    if (!content) {
      return {
        content: [
          {
            type: "text",
            text: `No destination guide found for id "${id}". Use list_destinations to see valid ids.`
          }
        ],
        isError: true
      };
    }
    const guide = {
      id: key,
      name: meta?.name ?? content.title ?? key,
      country: meta?.country,
      intro: toText(content.intro),
      hotels: (content.hotels ?? []).map((h) => ({
        name: h.name,
        description: h.description,
        location: h.location ?? h.address,
        website: h.website ?? h.websiteUrl,
        allergyInfo: h.allergyInfo,
        allergenFriendly: h.allergenFriendly
      })),
      restaurants: (content.restaurants ?? []).map((r) => ({
        name: r.name,
        description: r.description,
        cuisine: r.cuisine,
        location: r.location ?? r.address,
        allergyInfo: r.allergyInfo
      })),
      faqs: content.faqs ?? [],
      travelTips: content.travelTips ?? content.tips ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(guide, null, 2) }],
      structuredContent: { guide }
    };
  }
});

// src/lib/mcp/tools/search-hotels.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
import { destinationData as destinationData2 } from "npm:@/data/destination-data";
import { destinations as destinations3 } from "npm:@/data/destinations-list";
var search_hotels_default = defineTool3({
  name: "search_hotels",
  title: "Search allergy-friendly hotels",
  description: "Search allergy-friendly hotels across all destination guides by keyword (hotel name, destination, or allergy info). Returns matching hotels with the destination they belong to.",
  inputSchema: {
    query: z3.string().min(1).describe("Keyword, e.g. 'gluten-free London', 'nut-free', or a hotel name."),
    limit: z3.number().int().optional().describe("Max results to return. Defaults to 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, limit }) => {
    const q = query.trim().toLowerCase();
    const max = Math.max(1, Math.min(limit ?? 20, 50));
    const nameById = new Map(destinations3.map((d) => [d.id, d.name]));
    const results = [];
    for (const [id, content] of Object.entries(destinationData2)) {
      const destName = nameById.get(id) ?? id;
      for (const h of content.hotels ?? []) {
        const hay = [h.name, h.description, h.allergyInfo, destName, id, (h.allergenFriendly ?? []).join(" ")].filter(Boolean).join(" ").toLowerCase();
        if (hay.includes(q)) {
          results.push({
            name: h.name,
            destination: destName,
            destinationId: id,
            description: h.description,
            website: h.website ?? h.websiteUrl,
            allergyInfo: h.allergyInfo
          });
        }
        if (results.length >= max) break;
      }
      if (results.length >= max) break;
    }
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { count: results.length, hotels: results }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "allergy-friendly-travel-mcp",
  title: "Allergy-Friendly Travel MCP",
  version: "0.1.0",
  instructions: "Tools for the Allergy-Friendly Travel guide. Use list_destinations to browse destination guides, get_destination_guide to read a full guide (hotels, restaurants, FAQs, tips), and search_hotels to find allergy-friendly hotels by keyword.",
  tools: [list_destinations_default, get_destination_guide_default, search_hotels_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
